### ISSUE TITLE
Fix Network Packets... Something

### ISSUE THREAD

**Issue by yolp900** [yolp900/ItsJustaCharm#1]
WhenConstructionTableCreationEvent fires, it kicks the player out of the server and doesn't create the Construction Table. My guess is that it's something to do with the need for a network packet to be sent to the client to notify it of blocks changing.

**Comment by yolp900** [comment]
This is the current only server problem, at least that I've found in my testing.

**Comment by Aviv871** [comment]
@yolp900 was here

**Comment by yolp900** [comment]
So now we know... if (world.isRemote) for client side. servers dont like if(world.isRemote). but cool, were done with this annoying bug.
